# Generated by Django 3.1.4 on 2020-12-09 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20201209_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='firstname',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='post',
            name='lastname',
            field=models.CharField(max_length=255),
        ),
    ]
