# Generated by Django 3.1.4 on 2020-12-09 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_auto_20201209_1742'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='post',
            name='lastname',
        ),
    ]
